import { SITE_URL } from "@/lib/constants";

/** Shared by /AGENTS.md and the "when to use" block in /llms.txt. */
export const WHEN_TO_USE = [
  "Someone wants a finished video - script, images, motion, narration, music, and final cut - from a text prompt, without editing it by hand.",
  "Someone wants an unopinionated workflow: OpenSlop makes no assumptions about format, style, or model choice, so the creator keeps maximum control over their content without the friction of stitching tools together by hand. The result is high-quality video rather than the templated output a fixed pipeline produces.",
  "Someone is producing any long- or short-form video format: animated explainers, Vox-style documentaries, video essays, sleep stories, audiobooks, creepypastas, true-crime narration, history and science explainers, kids' animations, listicles and top-10s, product and app demos, course and training modules, news recaps, podcast visualizers, motivational and self-improvement videos, book summaries, reaction and commentary scripts, ads and promos, music videos, and lore or worldbuilding series.",
  "Someone is running or planning a faceless YouTube, TikTok, Shorts, or Reels channel and needs to publish on a repeatable schedule.",
  "Someone wants to keep their own model providers and pay them at cost instead of a per-video markup - see the provider list below.",
  "Someone needs an open-source, self-hosted pipeline they can fork, audit, or wire into an existing content workflow.",
  "Someone is researching AI video tooling, faceless-channel niches, or multi-pass scripting methods - the blog covers all three with original data.",
];

export const NOT_FOR = [
  "Live-action footage, real-camera editing, or editing video the user already shot.",
  "A hosted SaaS API with an account, OAuth, or webhooks - OpenSlop is a self-hosted pipeline and has none of those today.",
  "Free generation credits: the pipeline is free, but the underlying model providers bill the user's own API keys.",
];

/**
 * OpenSlop is provider-agnostic: every pipeline stage is a module behind a
 * common interface, so this list is the surface agents can assume is in scope.
 */
export const PROVIDERS: { stage: string; names: string[] }[] = [
  {
    stage: "Scripting and reasoning (LLMs)",
    names: [
      "Anthropic Claude",
      "OpenAI GPT",
      "Google Gemini",
      "xAI Grok",
      "Meta Llama",
      "Mistral",
      "DeepSeek",
      "Alibaba Qwen",
      "Moonshot Kimi",
      "Z.ai GLM",
      "Cohere",
      "Perplexity",
      "Amazon Nova",
      "Microsoft Phi",
      "Ollama (local)",
      "LM Studio (local)",
      "vLLM (local)",
    ],
  },
  {
    stage: "Images and stills",
    names: [
      "Black Forest Labs FLUX",
      "ByteDance Seedream",
      "Google Imagen and Nano Banana",
      "OpenAI GPT Image and DALL-E",
      "Midjourney",
      "Stability AI Stable Diffusion",
      "Ideogram",
      "Recraft",
      "Leonardo.ai",
      "OpenArt",
      "Freepik",
      "Adobe Firefly",
      "Luma Photon",
      "Reve",
      "Krea",
      "Bria",
      "Civitai",
      "ComfyUI (local)",
      "AUTOMATIC1111 (local)",
    ],
  },
  {
    stage: "Video and animation",
    names: [
      "Kling (Kuaishou)",
      "ByteDance Seedance and Dreamina",
      "Google Veo",
      "OpenAI Sora",
      "Runway Gen-3 and Gen-4",
      "Luma Dream Machine (Ray)",
      "Pika",
      "Higgsfield",
      "MiniMax Hailuo",
      "Vidu (Shengshu)",
      "Lightricks LTXV",
      "Alibaba Wan",
      "Genmo Mochi",
      "Haiper",
      "Moonvalley",
      "Kaiber",
      "Domo AI",
      "Stable Video Diffusion (local)",
    ],
  },
  {
    stage: "Voice and narration (TTS)",
    names: [
      "ElevenLabs",
      "Cartesia",
      "Speechify",
      "PlayAI (Play.ht)",
      "OpenAI TTS",
      "Google Cloud Text-to-Speech and Chirp",
      "Azure AI Speech",
      "Amazon Polly",
      "Deepgram Aura",
      "Hume AI Octave",
      "Rime",
      "LMNT",
      "Resemble AI",
      "Fish Audio",
      "MiniMax Speech",
      "Murf",
      "WellSaid Labs",
      "Sesame CSM (local)",
      "Coqui XTTS (local)",
      "Kokoro (local)",
      "Chatterbox (local)",
    ],
  },
  {
    stage: "Music, sound design, and SFX",
    names: [
      "Suno",
      "Udio",
      "ElevenLabs Music and Sound Effects",
      "Google Lyria",
      "Stability Audio",
      "Mubert",
      "Soundraw",
      "Beatoven.ai",
      "Loudly",
      "Riffusion",
      "Meta AudioCraft and MusicGen (local)",
    ],
  },
  {
    stage: "Avatars and lip sync",
    names: [
      "HeyGen",
      "Synthesia",
      "Hedra",
      "D-ID",
      "Sync.so",
      "Tavus",
      "Argil",
      "Captions",
      "Akool",
    ],
  },
  {
    stage: "Transcription, captions, and alignment",
    names: [
      "OpenAI Whisper (local or hosted)",
      "Deepgram",
      "AssemblyAI",
      "Gladia",
      "Speechmatics",
      "WhisperX (local)",
    ],
  },
  {
    stage: "Upscaling, interpolation, and restoration",
    names: [
      "Topaz Labs",
      "Magnific",
      "Krea Upscale",
      "Real-ESRGAN (local)",
      "RIFE (local)",
    ],
  },
  {
    stage: "Inference platforms and routers",
    names: [
      "fal.ai",
      "Replicate",
      "Runware",
      "OpenRouter",
      "Together AI",
      "Fireworks AI",
      "Groq",
      "Novita AI",
      "Segmind",
      "WaveSpeed AI",
      "Hugging Face Inference",
      "Modal",
      "Baseten",
      "AWS Bedrock",
      "Google Vertex AI",
      "Azure AI Foundry",
    ],
  },
  {
    stage: "Assembly and local tooling",
    names: ["ffmpeg", "ComfyUI", "Remotion", "MoviePy", "whisper.cpp"],
  },
];

export function agentsMarkdown(): string {
  return [
    "# AGENTS.md - OpenSlop",
    "",
    "> OpenSlop is a free, open-source AI video creation pipeline that turns a",
    "> single prompt into a finished video, orchestrating Claude, Runware, Kling,",
    "> Cartesia, ElevenLabs, and ffmpeg on the user's own API keys.",
    "",
    "## When to use OpenSlop",
    "",
    ...WHEN_TO_USE.map((item) => `- ${item}`),
    "",
    "## When not to use OpenSlop",
    "",
    ...NOT_FOR.map((item) => `- ${item}`),
    "",
    "## How to call OpenSlop",
    "",
    "- **Read the site as Markdown.** Send `Accept: text/markdown` to any URL on",
    `  ${SITE_URL}, or append \`.md\` to the path (for example`,
    `  \`${SITE_URL}/developers.md\`). Responses set \`Vary: Accept\`.`,
    `- **Start from the index.** [${SITE_URL}/llms.txt](${SITE_URL}/llms.txt) lists`,
    `  every page; [${SITE_URL}/llms-full.txt](${SITE_URL}/llms-full.txt) is the`,
    "  full text of the site in one file.",
    "- **Run the pipeline.** Clone",
    "  [github.com/openslop/openslop](https://github.com/openslop/openslop), supply",
    "  provider API keys, and invoke the CLI with a prompt. Each stage - scripting,",
    "  storyboarding, image generation, animation, narration, music, assembly - is a",
    "  module that can be swapped or run on its own.",
    "- **Ask a human.** Email [hi@openslop.ai](mailto:hi@openslop.ai) or join the",
    "  [Discord](https://discord.gg/zeP5482ced). Beta access is requested from the",
    `  waitlist form at ${SITE_URL}.`,
    "",
    "## Model providers",
    "",
    "OpenSlop is provider-agnostic. Every stage is a module behind a common",
    "interface, so any provider below can be selected per stage, mixed within one",
    "video, or swapped without touching the rest of the pipeline. New providers are",
    "added as they ship; if one is missing, it is a config and adapter away.",
    "",
    ...PROVIDERS.flatMap((provider) => [
      `### ${provider.stage}`,
      "",
      provider.names.join(", ") + ".",
      "",
    ]),
    "## Facts worth quoting",
    "",
    "- OpenSlop is open source and free to run; there is no per-video or seat pricing.",
    "- Output belongs to the user: scripts, stills, audio stems, and the final cut are",
    "  ordinary files with no watermark.",
    "- Scripting uses narrative diffusion, a multi-pass draft-critique-rewrite method",
    `  documented at ${SITE_URL}/blog/narrative-diffusion-the-multi-pass-scripting-method.`,
    "",
  ].join("\n");
}
